# Generated by Django 5.0.2 on 2024-11-25 23:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("actual_price", models.FloatField()),
                ("date_price", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Eur"),
                            ("USD", "Usd"),
                            ("GBP", "Gbp"),
                            ("JPY", "Jpy"),
                        ],
                        default="EUR",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("Crypto", "Crypto"), ("Bourse", "Bourse")],
                        max_length=10,
                    ),
                ),
                ("number", models.FloatField()),
                ("api_know", models.BooleanField(default=True)),
                ("company", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("ticker", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CashDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=50)),
                (
                    "account",
                    models.CharField(
                        choices=[
                            ("PEA", "Pea"),
                            ("CTO", "Cto"),
                            ("Ass_Vie", "Ass Vie"),
                            ("CSL_LEP", "Csl Lep"),
                            ("CC", "Cc"),
                            ("Livret_A", "Livret A"),
                            ("autre", "Autre"),
                        ],
                        default="CC",
                        max_length=50,
                    ),
                ),
                ("amount", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RealEstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="RealEstateDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Appartement", "Appartement"),
                            ("Maison", "Maison"),
                            ("Garage", "Garage"),
                            ("Commerce", "Commerce"),
                            ("Bureau", "Bureau"),
                            ("Immeuble", "Immeuble"),
                            ("Agricole", "Agricole"),
                            ("Autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("adresse", models.TextField(blank=True, null=True)),
                ("buy_date", models.DateTimeField()),
                ("buy_price", models.FloatField()),
                ("sell_date", models.DateTimeField(blank=True, null=True)),
                ("sell_price", models.FloatField(blank=True, null=True)),
                ("travaux_value", models.FloatField(blank=True, null=True)),
                ("other_costs", models.FloatField(blank=True, null=True)),
                ("notaire_costs", models.FloatField(blank=True, null=True)),
                ("apport", models.FloatField(blank=True, null=True)),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        choices=[("RP", "Rp"), ("RS", "Rs"), ("Location", "Location")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "type_rent",
                    models.CharField(
                        blank=True,
                        choices=[("Vide", "Vide"), ("LMNP", "Lmnp"), ("LMP", "Lmp")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("defisc", models.BooleanField(blank=True, default=False, null=True)),
                ("loyer_annuel", models.FloatField(blank=True, null=True)),
                ("charges_annuel", models.FloatField(blank=True, null=True)),
                ("taxe", models.FloatField(blank=True, null=True)),
                ("emprunt_costs", models.FloatField()),
                ("resteApayer", models.FloatField()),
                ("rate", models.FloatField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("actual_value", models.FloatField()),
                (
                    "actual_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "type_own",
                    models.CharField(
                        choices=[
                            ("Indivision", "Indivision"),
                            ("SCI", "Sci"),
                            ("Societe", "Societe"),
                            ("Propre", "Propre"),
                            ("Autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("part_own", models.IntegerField(blank=True, null=True)),
                (
                    "realestate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Wallet.realestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Wallet.asset",
                    ),
                ),
                (
                    "cash",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Wallet.cashdetail",
                    ),
                ),
                (
                    "RealEstate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Wallet.realestatedetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sells",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ticker", models.CharField(max_length=20, unique=True)),
                ("plateforme", models.CharField(blank=True, max_length=50, null=True)),
                ("account", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Eur"),
                            ("USD", "Usd"),
                            ("GBP", "Gbp"),
                            ("JPY", "Jpy"),
                        ],
                        default="EUR",
                        max_length=20,
                    ),
                ),
                ("number_sold", models.FloatField()),
                ("price_sold", models.FloatField()),
                ("date_sold", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sells",
                        to="Wallet.wallet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="realestate",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalImmo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCrypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalBourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CryptoDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sous_category",
                    models.CharField(
                        choices=[
                            ("BTC", "Btc"),
                            ("ETH", "Eth"),
                            ("Stablecoins", "Stablecoins"),
                            ("Altcoins", "Altcoins"),
                            ("NFT", "Nft"),
                        ],
                        max_length=20,
                    ),
                ),
                ("stacking", models.BooleanField(default=False)),
                ("number_stacking", models.IntegerField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.asset"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Bourse", "Bourse"),
                            ("Crypto", "Crypto"),
                            ("Cash", "Cash"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount_btc", models.FloatField()),
                ("amount_eth", models.FloatField()),
                ("amount_nft", models.FloatField()),
                ("amount_stablecoins", models.FloatField()),
                ("amount_altcoins", models.FloatField()),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cashdetail",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
            ),
        ),
        migrations.CreateModel(
            name="Cash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Bourse", "Bourse"),
                            ("Crypto", "Crypto"),
                            ("Cash", "Cash"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount_pea", models.FloatField()),
                ("amount_cto", models.FloatField()),
                ("amount_Ass_Vie", models.FloatField()),
                ("amount_CSL_LEP", models.FloatField()),
                ("amount_CC", models.FloatField()),
                ("amount_Livret_A", models.FloatField()),
                ("amount_autre", models.FloatField()),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Buy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Eur"),
                            ("USD", "Usd"),
                            ("GBP", "Gbp"),
                            ("JPY", "Jpy"),
                        ],
                        default="EUR",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("plateforme", models.CharField(blank=True, max_length=50, null=True)),
                ("account", models.CharField(blank=True, max_length=100, null=True)),
                ("number_buy", models.FloatField()),
                ("price_buy", models.FloatField()),
                ("date_buy", models.DateTimeField(default=django.utils.timezone.now)),
                ("ticker", models.CharField(max_length=20)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy",
                        to="Wallet.wallet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BourseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sous_category",
                    models.CharField(
                        choices=[
                            ("Action", "Action"),
                            ("ETF", "Etf"),
                            ("Forex", "Forex"),
                            ("Matieres_Premieres", "Matieres Premieres"),
                        ],
                        max_length=20,
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.asset"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Bourse", "Bourse"),
                            ("Crypto", "Crypto"),
                            ("Cash", "Cash"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount_action", models.FloatField()),
                ("amount_etf", models.FloatField()),
                ("amount_forex", models.FloatField()),
                ("amount_obligation", models.FloatField()),
                ("amount_matieres_premieres", models.FloatField()),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Wallet.wallet"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="Wallet.wallet",
            ),
        ),
    ]
