# Generated by Django 5.0.7 on 2024-12-01 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Wallet", "0002_alter_asset_date_price_alter_bourse_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprice",
            name="wallet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Wallet.wallet",
            ),
            preserve_default=False,
        ),
    ]
