# Generated by Django 5.0.7 on 2024-12-12 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_historicalprice_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatedetail',
            name='actual_date',
            field=models.DateField(default=datetime.date(2024, 12, 12)),
        ),
        migrations.AlterField(
            model_name='realestatedetail',
            name='emprunt_costs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='realestatedetail',
            name='type_own',
            field=models.CharField(choices=[('Indivision', 'Indivision'), ('SCI', 'Sci'), ('Societe', 'Societe'), ('Propre', 'Propre'), ('Autre', 'Autre')], default='Propre', max_length=50),
        ),
    ]
