# Generated by Django 5.0.7 on 2024-12-13 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_alter_realestatedetail_actual_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatedetail',
            name='actual_date',
            field=models.DateField(default=datetime.date(2024, 12, 13)),
        ),
    ]
