# Generated by Django 5.0.7 on 2024-09-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Crypto", "Crypto"),
                            ("Immo", "Immo"),
                            ("Bourse", "Bourse"),
                            ("Autre", "Autre"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=10, null=True)),
                ("company", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("ticker", models.CharField(max_length=10, unique=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("Euro", "Euro"), ("Dollar", "Dollar")],
                        default="Euro",
                        max_length=10,
                    ),
                ),
                ("last_value", models.FloatField()),
                ("date_value", models.DateTimeField()),
                ("market_cap", models.FloatField(blank=True, null=True)),
                ("trailing_return", models.FloatField(blank=True, null=True)),
                ("fee", models.FloatField(blank=True, null=True)),
                ("total_assets", models.FloatField(blank=True, null=True)),
                ("sector_weightings", models.JSONField(blank=True, null=True)),
                ("holding_percentages", models.JSONField(blank=True, null=True)),
                ("top_holdings", models.JSONField(blank=True, null=True)),
                ("beta", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("USD/EUR", "USD/EUR"),
                            ("EUR/USD", "EUR/USD"),
                            ("GBP/EUR", "GBP/EUR"),
                            ("EUR/GBP", "EUR/GBP"),
                            ("JPY/EUR", "JPY/EUR"),
                            ("EUR/JPY", "EUR/JPY"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="General.asset"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OneYearValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="General.asset"
                    ),
                ),
            ],
        ),
    ]
