# Generated by Django 5.0.7 on 2024-09-04 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("General", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="fee",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="holding_percentages",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="sector_weightings",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="top_holdings",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="total_assets",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="trailing_return",
        ),
    ]
