# Generated by Django 5.0.7 on 2024-09-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("General", "0004_alter_asset_category_alter_asset_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "Eur"),
                    ("USD", "Usd"),
                    ("GBP", "Gbp"),
                    ("JPY", "Jpy"),
                ],
                default="EUR",
                max_length=10,
            ),
        ),
    ]
