# Generated by Django 5.0.7 on 2024-11-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("General", "0006_alter_currency_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="date_value",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="currency",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="oldvalue",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="oneyearvalue",
            name="date",
            field=models.DateField(),
        ),
    ]
