# Generated by Django 5.0.7 on 2024-11-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("General", "0007_alter_asset_date_value_alter_currency_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="date_value",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="currency",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="oldvalue",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="oneyearvalue",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
