# Generated by Django 4.2.5 on 2025-02-17 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatedetail',
            name='actual_date',
            field=models.DateField(default=datetime.date(2025, 2, 17)),
        ),
    ]
