# Generated by Django 4.2.5 on 2025-03-02 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_alter_realestatedetail_actual_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestatedetail',
            name='actual_date',
            field=models.DateField(default=datetime.date(2025, 3, 2)),
        ),
    ]
