# Generated by Django 5.0.7 on 2024-08-16 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Community", "0002_rename_favoris_favori"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-date"]},
        ),
    ]
