# Generated by Django 5.0.7 on 2024-08-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Community", "0003_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="week",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subject",
            name="weekly_messages",
            field=models.IntegerField(default=0),
        ),
    ]
