# Generated by Django 5.0.7 on 2024-08-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Community", "0006_alter_keyword_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, unique=True, upload_to=""),
        ),
    ]
