# Generated by Django 5.0.7 on 2024-08-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Community", "0009_alter_message_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="Community.subject",
            ),
        ),
    ]
